### ISSUE TITLE
Use startup probe to get around slow RStudio container startup

### ISSUE THREAD

**Issue by tjpalanca** [tjpalanca/tjcloud#5]
Adding this to the service.yml:

```yaml
    health:
      startup:
        type: http
        endpoint: "/"
        success_threshold: 1
        failure_threshold: 60
        initial_delay: 30
        period: 30
```
